// Copyright (C) 2026 Joseph Morgridge
//
// Licensed under MIT License.
// See the LICENSE file in the project root for full license details.

export global Layout {
  out property <length> preferred-window-width: 960px;
  out property <length> preferred-window-height: 540px;  
  out property <length> window-padding: 10px;
  out property <length> panel-padding: 10px;
  out property <length> panel-spacing: 10px;
}