// Copyright (C) 2026 Joseph Morgridge
//
// Licensed under MIT License.
// See the LICENSE file in the project root for full license details.

// UI layer/view state (Slint)
export component ViewState {
  // Nothing here yet.
}

// App logic/model state (C++)
export global ModelState {
  in property <[string]> serial-ports;
  in property <[string]> baud-rates;
  in property <bool> serial-connected: false;

  callback open-github(string);
  callback refresh-serial-ports();
  callback connect-or-disconnect-serial(int, int) -> bool;
  callback send-byte-over-serial(int);
  callback up-clicked();
  callback left-clicked();
  callback right-clicked();
  callback down-clicked();
}
