// Copyright (C) 2026 Joseph Morgridge
//
// Licensed under MIT License.
// See the LICENSE file in the project root for full license details.

export global Theme {
  out property <length> default-font-size: 18px;
  out property <length> panel-border-radius: 10px;
  out property <color> panel-background: #093981;
  out property <length> text-font-size: default_font_size * (3/4);  
  out property <color> text-color: springgreen;
}