// Copyright (C) 2026 Joseph Morgridge
//
// Licensed under MIT License.
// See the LICENSE file in the project root for full license details.

import { Button } from "std-widgets.slint";
import { Version, Theme, Layout } from "../application/index.slint";
import { DraggableArea, Separator } from "../primitives/index.slint";

export component AboutPopup {
  visible: false;

  callback show();
  show() => { self.visible = true; }

  DraggableArea {
    Rectangle {
      border-radius: Theme.panel-border-radius;
      background: black;

      VerticalLayout {
        Rectangle {
          border-top-left-radius: Theme.panel-border-radius;
          border-top-right-radius: Theme.panel-border-radius;
          background: Colors.skyblue;

          Text { text: "  About This Application  "; }
        }

        Separator { height: 5px; }

        Text {
          text: "\{Version.name}\nVersion \{Version.major}.\{Version.minor}.\{Version.patch}";
          horizontal-alignment: center;
        }

        Separator { height: 10px; }
        
        Button {
          text: "Close";
          
          clicked() => { root.visible = false; }
        }
      }
    }
  }
}