import { StandardButton } from "std-widgets.slint";
import { Configuration, ModelState } from "../application/index.slint";

export component GitHubDialogue inherits Dialog {
  visible: false;

  callback show();
  show() => { self.visible = true; }

  Text { text: "This will open the GitHub page in your browser."; }

  StandardButton {
    kind: ok;

    clicked() => {
      ModelState.open-github(Configuration.github-url);
      root.visible = false; }
  }

  StandardButton {
    kind: cancel;

    clicked() => { root.visible = false; }
  }
}