import { StandardButton } from "std-widgets.slint";
import { Configuration } from "../configuration.slint";
import { ModelState } from "../state.slint";

export component GitHubDialogue inherits Dialog {
  visible: false;

  callback show();
  show() => { self.visible = true; }

  callback ok_clicked();

  Text { text: "This will open the GitHub page in your browser."; }

  StandardButton {
    kind: ok;

    clicked() => {
      ModelState.open_github(Configuration.github_url);
      root.visible = false; }
  }

  StandardButton {
    kind: cancel;

    clicked() => { root.visible = false; }
  }
}