import { AboutPopup } from "index.slint";

export component MainMenuBar inherits Window {
  callback github();
  about_popup := AboutPopup { y: 100px; }

  MenuBar {
    Menu {
      title: @tr("Help");
      
      MenuItem {
        title: @tr("About");
        activated => { about_popup.show(); }
      }

      //MenuSeparator {}
      
      MenuItem {
        title: @tr("GitHub");
        activated => { github(); }
      }
    }
  }
}