import { Configuration } from "../configuration.slint";
import { AboutPopup } from "about_popup.slint";
import { GitHubDialogue } from "github_dialogue.slint";

export component MainMenuBar inherits Window {
  callback open_github(string);

  about_popup := AboutPopup { y: 100px; }

  github_dialogue := GitHubDialogue {
    y: 100px;
    
    ok_clicked() => { root.open_github(Configuration.github_url); }
  }

  MenuBar {
    Menu {
      title: @tr("Help");
      
      MenuItem {
        title: @tr("About");
        activated => { about_popup.show(); }
      }

      //MenuSeparator {}
      
      MenuItem {
        title: @tr("GitHub");
        activated => { github_dialogue.show(); }
      }
    }
  }
}