// Copyright (C) 2026 Joseph Morgridge
//
// Licensed under MIT License.
// See the LICENSE file in the project root for full license details.

import { GridBox, Slider, TextEdit } from "std-widgets.slint";

export component HorizontalSlider {
  in-out property<string> title: "";

  in-out property<bool> enabled: true;
  out property<bool> has-focus <=> slider_used.has-focus;
  in-out property<float> value: 0;
  in-out property<float> step: 1;
  in-out property<float> minimum: 0;
  in-out property<float> maximum: 100;

  in-out property <bool> use-float: false;

  in-out property <length> text-font-size: 0px;
  in-out property<bool> text-enabled: true;
  out property<bool> text-has-focus <=> slider_text.has-focus;
  in-out property<bool> text-read-only: false;
  in-out property<TextWrap> text-wrap: no-wrap;

  callback changed(float);

  GridBox {
    padding: 0px;

    Text {
      row: 0;
      col: 0;
      text: title;
    }

    slider_text := TextEdit {
      row: 1;
      col: 0;
      font-size: text-font-size;
      wrap: text-wrap;
      enabled: text-enabled;
      read-only: text-read-only;
      text: value;
      
      edited(text) => {
        if (!text.is-float()) { return; }

        value = text.to-float();

        if (!use-float) {
          let value_int:int = value;
          value = value_int;
          self.text = value;
        }

        if (value > maximum) {
          value = maximum;
          self.text = value;
        }
        else if (value < minimum) { 
          value = minimum;
          self.text = value;
        }

        slider_used.value = value;
        slider_mask.value = maximum - value;

        changed(value);
      }
    }
    
    slider_used := Slider {
      row: 2;
      col: 0;
      enabled: enabled;
      orientation: horizontal;
      value: value;
      step: step;
      minimum: minimum;
      maximum: maximum;

      changed => {
        if (!use-float) {
          let value_int:int = self.value;
          root.value = value_int;
        }
        else { root.value = self.value; }
        
        slider_mask.value = maximum - root.value;
        slider_text.text = root.value;

        root.changed(root.value);
      }
    }

    slider_mask := Slider {
      row: 2;
      col: 0;
      z: -1; // Ensure slider_used is on top.
      enabled: enabled;
      orientation: horizontal;
      transform-rotation: 180deg;
      value: maximum - value;
      step: step;
      minimum: minimum;
      maximum: maximum;
    }
  } // Gridbox
}