import { GridBox, Slider, TextEdit } from "std-widgets.slint";

export component VerticalSlider {
  in-out property<string> title: "";

  in-out property<bool> enabled: true;
  out property<bool> has-focus <=> slider_used.has-focus;
  in-out property<float> value: 0;
  in-out property<float> step: 1;
  in-out property<float> minimum: 0;
  in-out property<float> maximum: 100;

  in-out property <bool> use-float: false;

  in-out property <length> text-font-size: 0px;  
  in-out property<bool> text-enabled: true;
  out property<bool> text-has-focus <=> slider_text.has-focus;
  in-out property<bool> text-read-only: false;
  in-out property<TextWrap> text-wrap: no-wrap;

  GridBox {
    padding: 0px;

    slider_used:= Slider {
      row: 0;
      col: 0;
      rowspan: 2;
      enabled: enabled;
      orientation: vertical;
      value: maximum - value;
      step: step;
      minimum: minimum;
      maximum: maximum;

      changed => {
        if (!use-float) {
          let value-int:int = maximum - self.value;
          value = value-int;
        }
        else { value = maximum - self.value; }

        slider_mask.value = value;
        slider_text.text = value;
      }
    }

    slider_mask := Slider {
      row: 0;
      col: 0;
      rowspan: 2;
      z: -1; // Ensure slider_used is on top.
      enabled: enabled;
      orientation: vertical;
      transform-rotation: 180deg;
      value: value;
      step: step;
      minimum: minimum;
      maximum: maximum;
    }

    Text {
      row: 0;
      col: 1;
      text: title;
    }

    slider_text := TextEdit {
      row: 1;
      col: 1;
      wrap: text-wrap;
      enabled: text-enabled;
      read-only: text-read-only;
      text: value;
      
      edited(text) => {
        if (!text.is-float()) { return; }

        value = text.to-float();

        if (!use-float) {
          let value_int:int = value;
          value = value_int;
          self.text = value;
        }

        if (value > maximum) {
          value = maximum;
          self.text = value;
        }
        else if (value < minimum) { 
          value = minimum;
          self.text = value;
        }

        slider_used.value = maximum - value;
        slider_mask.value = value;
      }
    }
  } // Gridbox
}