// Copyright (C) 2026 Joseph Morgridge
//
// Licensed under MIT License.
// See the LICENSE file in the project root for full license details.

import { Layout } from "../../application/index.slint";
import { MainTabs } from "main_tabs.slint";
import { IconPanel } from "icon_panel.slint";

export component HomePage {
  GridLayout {
    padding: Layout.window-padding;
    spacing: Layout.panel-spacing;    
    
    MainTabs {
      row: 0;
      col: 0;
    }

    IconPanel {
      row: 1;
      col: 0;
    }
  }
}