// Copyright (C) 2026 Joseph Morgridge
//
// Licensed under MIT License.
// See the LICENSE file in the project root for full license details.

import { Layout, Theme } from "../../application/index.slint";

export component IconPanel inherits Rectangle {
  border-radius: Theme.panel-border-radius;
  background: Theme.panel-background;

  in property <length> image-scale: 0.5px;

  GridLayout {
    padding: Layout.panel-padding;

    Image {
      source: @image-url("../../images/cogs.png");
      row: 0;
      col: 0;
      vertical-alignment: ImageVerticalAlignment.top;
      min-width: self.source.width * image-scale;
      min-height: self.source.height * image-scale;
      preferred-width: self.source.width * image-scale;
      preferred-height: self.source.height * image-scale;
      //image-fit: fill;
      colorize: Colors.goldenrod;
    }

    Image {
      source: @image-url("../../images/cloud.png");
      row: 1;
      col: 2;
      vertical-alignment: ImageVerticalAlignment.bottom;
      min-width: self.source.width * image-scale;
      min-height: self.source.height * image-scale;
      preferred-width: self.source.width * image-scale;
      preferred-height: self.source.height * image-scale;
      //image-fit: fill;
      colorize: skyblue;
    }      
  }
}