import { GridBox, Button, ComboBox } from "std-widgets.slint";
import { Layout, Theme, ModelState } from "../../application/index.slint";
import { Separator } from "../../primitives/index.slint";
import { VerticalSlider, HorizontalSlider, DPad } from "../../controls/index.slint";

export component MainPanel inherits Rectangle {
  private property <int> button-2-count: 0;
  private property <float> send-bytes-value: 0;

  private property <int> serial-ports-index;
  private property <int> baud-rates-index;

  border-bottom-left-radius: Theme.panel-border-radius;
  border-bottom-right-radius: Theme.panel-border-radius;
  background: Theme.panel-background;

  VerticalLayout {
    padding: Layout.panel-padding;
    
    // Button 1 and Button 2.
    GridBox {
      Row { // 0
        Button { // Col 0
          text: "Button 1";

          clicked => { root.button-2-count = 0; }
        }

        Separator {} // Col 1
        
        Button { // Col 2
          text: "Button 2";

          clicked() => { root.button-2-count += 1; }
        }
        
        Separator {} // Col 3

        Button { // Col 4
          text: "Refresh \nSerial Ports";
          rowspan: 2;

          clicked() => { ModelState.refresh-serial-ports(); }
        }

        ComboBox { // Col 5
          model: ModelState.serial-ports;
          current-index: root.serial-ports-index;

          selected(value) => { root.serial-ports-index = self.current-index; }
        }

        Text { text: "Port"; } // Col 6

        ComboBox { // Col 7
          model: ModelState.baud-rates;
          current-index: root.baud-rates-index;

          selected() => { root.baud-rates-index = self.current-index; }
        }

        Text { text: "Baud"; } // Col 8

        Button { // Col 9
          text: ModelState.serial-connected ? "Disconnect" : "Connect";

          clicked() => {
            ModelState.serial-connected = ModelState.connect-or-disconnect-serial(root.serial-ports-index, root.baud-rates-index);
          }
        }

        Separator { col: 15; }
      } // Row 0

      Row { // 1
        Text { // Col 0
          text: "Click to reset \nButton 2 clicks.";
          font-size: Theme.text-font-size;
          color: Theme.text-color;
        }

        Separator {} // Col 1
      
        Text { // Col 2
          text: "No. of clicks: " + button-2-count;
          font-size: Theme.text-font-size;
          color: Theme.text-color;
          col: 2;
        }
      }
    } // GridBox
    
    Separator {}

    // Button 3, Button 4, Slider 1, D-pad, Slider 2, Send.
    GridBox {
      // Col 0
        button_3 := Button {
          text: "Button 3";
          row: 0;
          col: 0;
          checkable: true;

          clicked => {
            if (self.checked) {
              button_4.checked = false;
              send-bytes-value = slider_1.value;
            }
            else {
              send-bytes-value = 0;
            }
          }
        }

        Text {
          text: "Toggle on to Send Slider 1 \nvalue over serial when \n\"Send Byte\" is clicked\n";
          font-size: Theme.text-font-size;
          color: Theme.text-color;
          row: 1; 
          col: 0;
        }

        button_4 := Button {
          text: "Button 4";
          row: 2;
          col: 0;
          checkable: true;

          clicked => {
            if (self.checked) {
              button_3.checked = false;
              send-bytes-value = slider_2.value;
            }
            else {
              send-bytes-value = 0;
            }
          }          
        }

        Text {
          text: "Toggle on to send Slider 2 \nvalue over serial when \n\"Send Byte\" is clicked\n";
          font-size: Theme.text-font-size;
          color: Theme.text-color;
          row: 3; 
          col: 0;
        }        

      // Col 1
        Separator { 
          row: 0; 
          col: 1; 
        }

      // Col 2
        slider_1 := VerticalSlider {
          title: "Slider 1";
          row: 0;
          col: 2;
          rowspan: 3;
          value: 60;

          changed(value) => {
            if (button_3.checked) { send-bytes-value = slider_1.value; }
          }
        }

      // Col 3
        Separator {
          row: 0;
          col: 3;
        }

      // Col 4
        DPad {
          up-icon: @image-url("../../images/up-icon.png");
          left-icon: @image-url("../../images/left-icon.png");
          right-icon: @image-url("../../images/right-icon.png");
          down-icon: @image-url("../../images/down-icon.png");
          row: 0;
          col: 4;
          rowspan: 3;
          up-colorize-icon: true;
          left-colorize-icon: true;
          right-colorize-icon: true;
          down-colorize-icon: true;

          up-clicked() => { ModelState.up-clicked(); }
          left-clicked() => { ModelState.left-clicked(); }
          right-clicked() => { ModelState.right-clicked(); }
          down-clicked() => { ModelState.down-clicked(); }
        }

      // Col 5
        Separator {
          row: 0;
          col: 5;
        }

      // Col 6
        slider_2 := HorizontalSlider {
          title: "Slider 2     ";
          row: 0;
          col: 6;
          rowspan: 3;
          value: 40;

          changed(value) => {
            if (button_4.checked) { send-bytes-value = slider_2.value; }
          }          
        }

      // Col 7
        Separator {
          row: 0;
          col: 7;
        }

      // Col 8
        Button {
          text: "Send Byte \n over Serial";
          row: 0;
          col: 8;
          rowspan: 2;

          clicked => { ModelState.send-byte-over-serial(send-bytes-value); }
        }

        Text {
          text: "Value to send: " + send-bytes-value;
          font-size: Theme.text-font-size;
          horizontal-alignment: center;
          color: Theme.text-color;
          row: 2;
          col: 8;
        }

        Separator { row: 0; col: 10; }
        
    } // Gridbox

    Separator {}
  } // VerticalLayout
}