import { Version } from "../version.slint";
import { Theme } from "../theme.slint";
import { Layout } from "../layout.slint";

export component AboutPopupPanel {//inherits Rectangle {
  width: 100%;
  height:100%;

  Rectangle {
    border-radius: Theme.panel_border_radius;
    background: Colors.darkred;

    VerticalLayout {
      padding: Layout.panel_padding;

      Text {
        text: "\{Version.name}\nVersion \{Version.major}.\{Version.minor}.\{Version.patch}";
      }
    }
  }
}