import { Button, VerticalBox } from "std-widgets.slint";
import { Layout } from "../layout.slint";
import { Theme } from "../theme.slint";

export component HomeMainPanel {
  Rectangle {
    border-radius: Theme.panel_border_radius;
    background: Theme.panel_background;
//*
    in-out property<int> counter: 42;
    callback request-increase-value();    
    VerticalBox {
      Text {
        text: "Counter: \{counter}";
      }
      Button {
        text: "Increase value";
        clicked => {
          request-increase-value();
        }
      }
    }
//*/  
  }
}