import { Version } from "version.slint";
import { Theme } from "theme.slint";
import { Layout } from "layout.slint";
import { Configuration } from "configuration.slint";
import { Page } from "navigation/index.slint";
import { HomePage, SplashPage } from "pages/index.slint";
import { MainMenuBar } from "menubar/main_menu_bar.slint";

export component AppWindow inherits Window {
  property<Page> page: Page.Splash;

  title: Version.name;

  default-font-size: Theme.default_font_size;

  preferred-width: Layout.preferred_window_width;
  preferred-height: Layout.preferred_window_height;
  
  Timer {
    interval: Configuration.splash_page_duration;
    running: true;
    triggered() => {
        page = Page.Home;
        self.running = false;
    }
  }

  VerticalLayout { // Required to maintain implicit sizes.
    if (page != Page.Splash):
    MainMenuBar { z: 1;}

    if (page == Page.Splash): 
    SplashPage {}

    if (page == Page.Home): 
    HomePage {}
  }
}
