import { Layout, Colours } from "theme.slint";

export component LogoPanel {
  x: Layout.panel_x;
  y: 0;
  width: Layout.panel_width;
  height: 150px;
  
  Rectangle {
    border-radius: Layout.panel_border_radius;
    background: Colours.panel_background;

    GridLayout {
      Image {
        source: @image-url("images/cogs.png");
        row: 0;
        col: 0;
      }
      Image {
        source: @image-url("images/cloud.png");     
        row: 1;
        col: 2;
      }      
    }

  }
}