// UI layer/view state (Slint)
export component ViewState {
  // Nothing here yet.
}

// App logic/model state (C++)
export global ModelState {
  in property <[string]> serial_ports;
  in property <int> serial_ports_index;
  in property <[string]> baud_rates: ["9600", "19200", "38400", "57600", "115200"];
  in property <int> baud_rates_index;

  callback open_github(string);
  callback refresh_serial_ports();
  callback connect_serial();
}
