// UI layer/view state (Slint)
export component ViewState {
  // Nothing here yet.
}

// App logic/model state (C++)
export global ModelState {
  in property <[string]> serial_ports;
  in property <int> serial_ports_index;
  in property <[string]> baud_rates;
  in property <int> baud_rates_index;
  in property <string> serial_connection_info;

  callback open_github(string);
  callback refresh_serial_ports();
  callback connect_or_disconnect_serial();
}
